import { AppLayout } from '@/components/AppSidebar'
import { prisma } from '@/lib/prisma'
import { requireClient } from '@/lib/rbac'
import { Playfair_Display } from 'next/font/google'
import { DollarSign, Activity, Clock } from 'lucide-react'

const heading = Playfair_Display({ subsets: ['latin'], weight: ['600', '700'] })

export default async function ClientBillingPage() {
  const context = await requireClient()

  const [entries, agg] = await Promise.all([
    prisma.creditLedger.findMany({
      where: { tenantId: context.tenantId! },
      orderBy: { createdAt: 'desc' },
      take: 100,
    }),
    prisma.creditLedger.aggregate({
      where: { tenantId: context.tenantId! },
      _sum: { amount: true },
    }),
  ])

  const balance = agg._sum.amount ? Number(agg._sum.amount) : 0
  const debits = entries.filter((e) => (e.eventType || '').includes('DEBIT'))
  const totalDebits = debits.reduce((sum, e) => sum + Number(e.amount), 0)

  return (
    <AppLayout>
      <div className="min-h-screen bg-[#0e0f12]">
        <div className="max-w-[1400px] mx-auto px-8 py-8 space-y-8">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div className="space-y-1.5">
              <h1 className={`${heading.className} text-3xl font-semibold text-white tracking-tight`}>
                Usage & Billing
              </h1>
              <p className="text-sm text-white/40 font-mono">
                Credit movements generated by your policy-evaluated access
              </p>
            </div>
          </div>

          {/* Summary cards */}
          <div className="grid gap-3 md:grid-cols-3">
            <div className="bg-white/[0.02] border border-white/[0.04] rounded-xl p-5">
              <p className="text-xs font-medium text-white/80">Current Balance</p>
              <p className="text-2xl font-semibold text-white mt-1 font-mono flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-white/60" />
                {balance.toFixed(2)}
              </p>
              <p className="text-xs text-white/50 mt-1">Positive = credits available for usage</p>
            </div>

            <div className="bg-white/[0.02] border border-white/[0.04] rounded-xl p-5">
              <p className="text-xs font-medium text-white/80">Total Debits (sample)</p>
              <p className="text-2xl font-semibold text-white mt-1 font-mono">
                {Math.abs(totalDebits).toFixed(2)}
              </p>
              <p className="text-xs text-white/50 mt-1">Usage-based charges in the last {entries.length} entries</p>
            </div>

            <div className="bg-white/[0.02] border border-white/[0.04] rounded-xl p-5">
              <p className="text-xs font-medium text-white/80">Ledger Entries</p>
              <p className="text-2xl font-semibold text-white mt-1 font-mono">{entries.length}</p>
              <p className="text-xs text-white/50 mt-1">Most recent movements only</p>
            </div>
          </div>

          {/* Ledger table */}
          <div className="bg-white/[0.02] border border-white/[0.04] rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-white/[0.02] border-b border-white/[0.04]">
                  <tr>
                    <th className="text-left px-4 py-2 text-xs font-medium text-white/60">When</th>
                    <th className="text-left px-4 py-2 text-xs font-medium text-white/60">Type</th>
                    <th className="text-left px-4 py-2 text-xs font-medium text-white/60">Amount</th>
                    <th className="text-left px-4 py-2 text-xs font-medium text-white/60">Policy / Dataset</th>
                    <th className="text-left px-4 py-2 text-xs font-medium text-white/60">Description</th>
                  </tr>
                </thead>
                <tbody>
                  {entries.length > 0 ? (
                    entries.map((entry) => (
                      <tr
                        key={entry.id}
                        className="border-b border-white/[0.04] hover:bg-white/[0.02] transition-colors"
                      >
                        <td className="px-4 py-2 text-xs text-white/60 font-mono">
                          <Clock className="h-3 w-3 inline mr-1" />
                          {new Date(entry.createdAt).toLocaleString()}
                        </td>
                        <td className="px-4 py-2 text-xs">
                          <span
                            className={`px-2 py-0.5 rounded text-[10px] font-medium ${
                              (entry.eventType || '').includes('DEBIT')
                                ? 'bg-white/5 text-white/70'
                                : 'bg-white/10 text-white/90'
                            }`}
                          >
                            {entry.eventType}
                          </span>
                        </td>
                        <td className="px-4 py-2 text-xs font-mono text-white/80">
                          {Number(entry.amount).toFixed(2)}
                        </td>
                        <td className="px-4 py-2 text-xs text-white/60 max-w-[220px] truncate">
                          {(entry.metadata as any)?.policyId || '-'}
                          {(entry.metadata as any)?.datasetName ? ` • ${(entry.metadata as any).datasetName}` : ''}
                        </td>
                        <td className="px-4 py-2 text-xs text-white/60 max-w-[260px] truncate">
                          {entry.description || entry.eventType}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={5} className="px-4 py-6 text-center text-xs text-white/50">
                        <Activity className="h-4 w-4 inline mr-2 text-white/30" />
                        No billing activity yet for this AI Lab.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  )
}
