/**
 * Cross-Modal Token Generator
 * Generates consistent patient tokens across all modalities
 * HMAC-based with tenant secret + dataset salt
 */

import { createHmac, randomBytes } from 'crypto';

export interface TokenConfig {
  tenantSecret: string;
  datasetSalt: string;
  version: number;
  rotationDate?: Date;
}

export interface PatientToken {
  token: string;
  version: number;
  createdAt: Date;
  modalities: string[];
}

export interface TokenMetadata {
  originalId: string;
  token: string;
  version: number;
  salt: string;
  appliedAt: Date;
}

export class CrossModalTokenGenerator {
  private config: TokenConfig;
  private tokenCache: Map<string, PatientToken> = new Map();

  constructor(config: TokenConfig) {
    this.config = {
      ...config,
    };
  }

  /**
   * Generate a consistent token for a patient across all modalities
   * Uses HMAC(patient_identifier, tenant_secret + dataset_salt)
   */
  generateToken(
    patientIdentifier: string,
    modalities: Array<'text' | 'dicom' | 'audio' | 'claims'> = ['text', 'dicom', 'audio', 'claims']
  ): PatientToken {
    // Check cache first
    const cacheKey = `${patientIdentifier}:${this.config.version}`;
    if (this.tokenCache.has(cacheKey)) {
      return this.tokenCache.get(cacheKey)!;
    }

    // Generate token using HMAC
    const data = `${patientIdentifier}:${this.config.datasetSalt}`;
    const hmac = createHmac('sha256', this.config.tenantSecret);
    hmac.update(data);
    const token = `ptk_${hmac.digest('hex').substring(0, 16)}`;

    const patientToken: PatientToken = {
      token,
      version: this.config.version,
      createdAt: new Date(),
      modalities: [...modalities],
    };

    // Cache the result
    this.tokenCache.set(cacheKey, patientToken);

    return patientToken;
  }

  /**
   * Generate tokens for multiple patients in batch
   */
  batchGenerateTokens(
    patientIdentifiers: string[],
    modalities?: Array<'text' | 'dicom' | 'audio' | 'claims'>
  ): Map<string, PatientToken> {
    const results = new Map<string, PatientToken>();

    for (const id of patientIdentifiers) {
      const token = this.generateToken(id, modalities);
      results.set(id, token);
    }

    return results;
  }

  /**
   * Rotate token version while maintaining reproducibility
   * New tokens use new version, old tokens still valid for lookup
   */
  rotateVersion(newSecret: string, newSalt: string): CrossModalTokenGenerator {
    return new CrossModalTokenGenerator({
      tenantSecret: newSecret,
      datasetSalt: newSalt,
      version: this.config.version + 1,
      rotationDate: new Date(),
    });
  }

  /**
   * Verify that a token was generated by this generator
   */
  verifyToken(patientIdentifier: string, token: string): boolean {
    const expected = this.generateToken(patientIdentifier);
    return expected.token === token;
  }

  /**
   * Apply token to all modalities for a patient record
   * Must be called BEFORE linking/timeline creation
   */
  applyTokenToRecord<T extends { patientId: string }>(
    record: T,
    modalities: Array<'text' | 'dicom' | 'audio' | 'claims'>
  ): T & { patientToken: string; tokenVersion: number; tokenAppliedAt: Date } {
    const token = this.generateToken(record.patientId, modalities);

    return {
      ...record,
      patientToken: token.token,
      tokenVersion: token.version,
      tokenAppliedAt: new Date(),
    };
  }

  /**
   * Apply tokens to a batch of records
   */
  batchApplyTokens<T extends { patientId: string }>(
    records: T[],
    modalities: Array<'text' | 'dicom' | 'audio' | 'claims'>
  ): Array<T & { patientToken: string; tokenVersion: number; tokenAppliedAt: Date }> {
    return records.map((record) => this.applyTokenToRecord(record, modalities));
  }

  /**
   * Generate consistent token for linking across modalities
   * Same patient always gets same token regardless of source
   */
  generateLinkToken(
    patientIdentifier: string,
    sourceModality: string,
    targetModality: string
  ): string {
    const baseToken = this.generateToken(patientIdentifier);
    // Link tokens include modality info for verification
    const linkData = `${baseToken.token}:${sourceModality}:${targetModality}`;
    const hmac = createHmac('sha256', this.config.tenantSecret);
    hmac.update(linkData);
    return `lnk_${hmac.digest('hex').substring(0, 12)}`;
  }

  /**
   * Get token statistics
   */
  getStats(): {
    version: number;
    cacheSize: number;
    saltLength: number;
    hasRotationDate: boolean;
  } {
    return {
      version: this.config.version,
      cacheSize: this.tokenCache.size,
      saltLength: this.config.datasetSalt.length,
      hasRotationDate: !!this.config.rotationDate,
    };
  }

  /**
   * Clear token cache
   */
  clearCache(): void {
    this.tokenCache.clear();
  }

  /**
   * Generate a random salt for new dataset
   */
  static generateSalt(): string {
    return randomBytes(16).toString('hex');
  }

  /**
   * Create generator from existing configuration
   */
  static fromConfig(config: {
    tenantSecret: string;
    datasetId: string;
    version?: number;
  }): CrossModalTokenGenerator {
    // Derive dataset-specific salt from datasetId
    const salt = createHmac('sha256', config.tenantSecret)
      .update(config.datasetId)
      .digest('hex')
      .substring(0, 16);

    return new CrossModalTokenGenerator({
      tenantSecret: config.tenantSecret,
      datasetSalt: salt,
      version: config.version ?? 1,
    });
  }
}

/**
 * Token registry for tracking all tokens in a dataset
 */
export class TokenRegistry {
  private tokens: Map<string, TokenMetadata> = new Map();

  register(
    originalId: string,
    token: string,
    version: number,
    salt: string
  ): void {
    this.tokens.set(originalId, {
      originalId,
      token,
      version,
      salt,
      appliedAt: new Date(),
    });
  }

  lookup(originalId: string): TokenMetadata | undefined {
    return this.tokens.get(originalId);
  }

  reverseLookup(token: string): TokenMetadata | undefined {
    for (const meta of this.tokens.values()) {
      if (meta.token === token) {
        return meta;
      }
    }
    return undefined;
  }

  getAllTokens(): TokenMetadata[] {
    return Array.from(this.tokens.values());
  }

  exportRegistry(): {
    version: string;
    createdAt: string;
    tokens: TokenMetadata[];
  } {
    return {
      version: '1.0',
      createdAt: new Date().toISOString(),
      tokens: this.getAllTokens(),
    };
  }
}
