-- Add 2FA and Email OTP fields to User
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "emailOtpCode" TEXT,
  ADD COLUMN IF NOT EXISTS "emailOtpExpires" TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "totpSecret" TEXT,
  ADD COLUMN IF NOT EXISTS "twoFactorVerifiedAt" TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS "twoFactorBackupCodes" TEXT;
