apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xase-sheets.fullname" . }}
  labels:
    {{- include "xase-sheets.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  nextauth-secret: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  nextauth-url: {{ .Values.secrets.nextauthUrl | b64enc | quote }}
  stripe-secret-key: {{ .Values.secrets.stripeSecretKey | b64enc | quote }}
  stripe-webhook-secret: {{ .Values.secrets.stripeWebhookSecret | b64enc | quote }}
  smtp-user: {{ .Values.secrets.smtpUser | b64enc | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  audit-signing-key: {{ .Values.secrets.auditSigningKey | b64enc | quote }}
