import { CompilationResult, PreparationRequest } from '../preparation.types';
import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

export interface PackageResult {
  manifestPath: string;
  checksumPath: string;
  readmePath: string;
}

export class Packager {
  async package(
    datasetId: string,
    compilation: CompilationResult,
    request: PreparationRequest
  ): Promise<PackageResult> {
    const outputDir = `/tmp/preparation/${datasetId}`;

    const manifest = await this.createManifest(compilation, request);
    const manifestPath = path.join(outputDir, 'manifest.json');
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2));

    const checksums = await this.createChecksums(compilation.outputPaths);
    const checksumPath = path.join(outputDir, 'checksums.txt');
    await fs.writeFile(checksumPath, checksums);

    const readme = this.createReadme(compilation, request);
    const readmePath = path.join(outputDir, 'README.md');
    await fs.writeFile(readmePath, readme);

    return { manifestPath, checksumPath, readmePath };
  }

  private async createManifest(
    compilation: CompilationResult,
    request: PreparationRequest
  ): Promise<unknown> {
    return {
      version: '1.0',
      task: request.task,
      modality: request.modality,
      target: request.target,
      compilation: {
        format: compilation.format,
        shardCount: compilation.shardCount,
        totalSizeBytes: compilation.totalSizeBytes,
        recordCount: compilation.recordCount,
      },
      files: compilation.outputPaths.map((p) => path.basename(p)),
      createdAt: new Date().toISOString(),
    };
  }

  private async createChecksums(filePaths: string[]): Promise<string> {
    const checksums: string[] = [];

    for (const filePath of filePaths) {
      const content = await fs.readFile(filePath);
      const hash = crypto.createHash('sha256').update(content).digest('hex');
      checksums.push(`${hash}  ${path.basename(filePath)}`);
    }

    return checksums.join('\n') + '\n';
  }

  private createReadme(compilation: CompilationResult, request: PreparationRequest): string {
    return `# Dataset Preparation Output

## Overview
- **Task**: ${request.task}
- **Modality**: ${request.modality}
- **Target Runtime**: ${request.target.runtime}
- **Format**: ${request.target.format}

## Compilation Results
- **Shards**: ${compilation.shardCount}
- **Total Size**: ${(compilation.totalSizeBytes / (1024 * 1024)).toFixed(2)} MB
- **Records**: ${compilation.recordCount}

## Files
${compilation.outputPaths.map((p) => `- ${path.basename(p)}`).join('\n')}

## Usage
Load this dataset using your training framework. See manifest.json for detailed metadata.

## Verification
Verify file integrity using checksums.txt:
\`\`\`bash
sha256sum -c checksums.txt
\`\`\`

---
Generated by XASE Data Preparation Pipeline
`;
  }
}
